# fly.toml app configuration file generated for mysql-regens-unite on 2023-07-26T15:31:35+02:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "mysql-regens-unite"
primary_region = "ams2"
kill_signal = "SIGINT"
kill_timeout = "5s"

[[mounts]]
  # NOTE: this volume was previously created with `fly volumes create mysql_regens_unite --size 1`
  # NOTE: 1GB of storage provided, to stay within free tier
  source="mysql_regens_unite"
  # NOTE: this should be a parent of the folder configured by --datadir (see below)
  destination="/data"
  processes=["app"]

[env]
  MYSQL_DATABASE = "passbolt_1"
  MYSQL_USER = "bb6d5879"

[build]
  dockerfile = "Dockerfile"

[experimental]
  auto_rollback = true
  cmd = [
    "--default-authentication-plugin",
    "mysql_native_password",
    "--datadir",
    "/data/mysql",
    # NOTE: two lines below ensure MYSQL 8 can work with the RAM available in the free tier,
    #       see: https://fly.io/docs/app-guides/mysql-on-fly/#scale-the-app
    "--performance-schema=OFF",
    "--innodb-buffer-pool-size", "64M"
  ]
