# fly.toml file generated for mysql-regens-unite on 2022-12-01T17:49:19+01:00

app = "mysql-regens-unite"
kill_signal = "SIGINT"
kill_timeout = 5
processes = []

[mounts]
  # NOTE: this volume was previously created with `fly volumes create mysql_regens_unite --size 1`
  # NOTE: 1GB of storage provided, to stay within free tier
  source="mysql_regens_unite"
  # NOTE: this should be a parent of the folder configured by --datadir (see below)
  destination="/data"

[env]
  MYSQL_DATABASE = "passbolt_1"
  MYSQL_USER = "bb6d5879"

[build]
  image = "mysql:8"

[experimental]
  allowed_public_ports = []
  auto_rollback = true
  cmd = [
    "--default-authentication-plugin",
    "mysql_native_password",
    "--datadir",
    "/data/mysql",
    # NOTE: two lines below ensure MYSQL 8 can work with the RAM available in the free tier
    "--performance-schema=OFF",
    "--innodb-buffer-pool-size", "64M"
  ]
